### ISSUE TITLE
Share announcement texts to help organizations and partners and volunteers to advertize

### ISSUE THREAD

**Issue by bast** [coderefinery/2022-09-20-workshop#4]

**Comment by samumantha** [comment]
Suggestion based on Lucas suggestion from March workshop:

Do you write code for your research? Do you manage data? Most importantly, are you doing it properly? Has it ever happened to you to have to rewrite or simply copy-paste codes from one folder to another, possibly losing things during the process? Have you ever opened an old code you wrote and had no clue what it does? Maybe you feel you waste a lot of time doing a lot of manual work to process your data and would like to automate it? Or maybe you also are not doing any of this yet, but would like to avoid these issues from happening in the future and do things properly from the beginning?

If you answered yes to any of the previous questions, then you are strongly encouraged to participate to the CodeRefinery Workshop on 20-22 September and 27-29 September, it will be fully online and free. Topics covered in the workshop include

-     using git to maintain your codes and collaborate with others
-     Principles of reproducible research and FAIR
-     Good coding practices in general (writing documentation, testing, how to choose an appropriate license)

The Workshop will not teach you to code, but all the "good practice skills" that are needed to write good maintainable software and achieve reproducible research.

The workshop will alternate type along tutorials given by instructors to break-out room exercises where you will get to practice. Each breakout room will have an exercise leader to help you. You can also register as a team, in which case the team will be in the same break out room (you can also exercise together in-person if you prefer), each team can propose their own exercise leader otherwise they will be assigned one. If you already have some experience and would like to strengthen your skills and help others, you can also volunteer as an exercise leader. Some places also offer in-person exercise sessions, check if there is a session offered near you from the workshop page below. 

More information and registration form on the workshop page: https://coderefinery.github.io/2022-09-20-workshop/

**Comment by bast** [comment]
Latest version is here: https://coderefinery.github.io/2022-09-20-workshop/announcements/
